name: Deploy Frontend to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package.json'
      - 'vite.config.js'
      - 'Dockerfile'
      - 'nginx.conf*'
      - 'docker-entrypoint.sh'
      - '.github/workflows/deploy-frontend.yml'
  pull_request:
    branches: [ main ]

concurrency:
  group: "deploy-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build frontend
      env:
        VITE_API_BASE_URL: https://web-production-de0bc.up.railway.app
        NODE_ENV: production
      run: npm run build
      
    - name: Run tests
      run: npm test -- --coverage --watchAll=false
      continue-on-error: true
      
    - name: Install Railway CLI
      if: github.ref == 'refs/heads/main'
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo "$HOME/.railway/bin" >> $GITHUB_PATH
        
    - name: Deploy to Railway
      if: github.ref == 'refs/heads/main'
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        export RAILWAY_TOKEN="${{ secrets.RAILWAY_TOKEN }}"
        railway up --detach
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: dist/
        retention-days: 7